In [110]:
import pandas as pd
import numpy as np

In [111]:
np.random.seed(0)
df = pd.DataFrame({
    'x': [0,0,1,0,0,1,1,0,0,1,0,0,1,1,0,0,1,0,0,1,1],
    'y': [28,24,26,24,23,28,24,26,25,28,21,22,27,26,26,21,21,27,23,22,24],
    'sale': [1,0,0,0,0,1,0,1,0,1,0,0,1,1,0,0,1,0,0,0,1]
})

In [112]:
df

x   y  sale
0   0  28     1
1   0  24     0
2   1  26     0
3   0  24     0
4   0  23     0
5   1  28     1
6   1  24     0
7   0  26     1
8   0  25     0
9   1  28     1
10  0  21     0
11  0  22     0
12  1  27     1
13  1  26     1
14  0  26     0
15  0  21     0
16  1  21     1
17  0  27     0
18  0  23     0
19  1  22     0
20  1  24     1

In [113]:
from sklearn.linear_model import LogisticRegression

In [114]:
X = df.iloc[:, :2]
y = df.iloc[:, -1]
lr = LogisticRegression(C=0.01)
lr.fit(X, y)

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [115]:
lr.coef_

array([[ 0.023, -0.016]])

In [116]:
lr.intercept_

array([-0.005])

In [217]:
def f(x1, x2):
    x =  (2.44*x1 +  0.54*x2 - 15.20)
    x1 = 1/ (1 + np.exp(-x))
    return x1

In [218]:
f(X.values[:, 0], X.values[:, 1])

array([0.48 , 0.096, 0.782, 0.096, 0.058, 0.914, 0.55 , 0.239, 0.154,
       0.914, 0.021, 0.035, 0.861, 0.782, 0.239, 0.021, 0.195, 0.35 ,
       0.058, 0.293, 0.55 ])

In [156]:
lr.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [157]:
lr.score(X,y)

0.619

In [200]:
x5 = (2.44 * 1)+ (0.54*24) - 15.20
x5

0.200

In [201]:
1/ (1 + np.exp(-0.2))

0.550

In [213]:
X.values[:, 0]

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1])